name: CI workflow for development environment

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js and cache dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v2
      with:
          path: ~/.npm
          key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-v2-${{ env.cache-name }}-
            ${{ runner.os }}-build-v2-
            ${{ runner.os }}-v2-

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: npm ci

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Save artifacts
      uses: actions/upload-artifact@main
      with:
        name: webpack artifacts
        path: public/

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@main
      with: 
        name: webpack artifacts
        path: public
    - name: Restore node_modules from cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-v2-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
            ${{ runner.os }}-build-v2-${{ env.cache-name }}-
            ${{ runner.os }}-build-v2-
            ${{ runner.os }}-v2-
    - name: Testing - Jest
      run: |
        npm ci
        npm run test

  test_api:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Testing API - Newman
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
        POSTMAN_COLLECTION_UID: ${{ secrets.POSTMAN_COLLECTION_UID }}
        POSTMAN_DEV_ENVIRONMENT_UID: ${{ secrets.POSTMAN_DEV_ENVIRONMENT_UID }}
      run:
        newman run https://api.getpostman.com/collections/"$POSTMAN_COLLECTION_UID"?apikey="$POSTMAN_API_KEY" --environment https://api.getpostman.com/environments/"$POSTMAN_DEV_ENVIRONMENT_UID"?apikey="$POSTMAN_API_KEY"

